# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:title/

# Setup
title: 'Swift Weekly Brief'
tagline: 'A community-driven weekly newsletter about Swift.org'
timezone: America/Los_Angeles

url: https://swiftweekly.github.io
handle: '@swiftlybrief'

author:
  name: 'Jesse Squires'
  url: https://twitter.com/jesse_squires

excerpt_separator: <!--excerpt-->

links:
  twitter: 'https://twitter.com/swiftlybrief'
  github: 'https://github.com/SwiftWeekly/swiftweekly.github.io'
  issue: 'https://github.com/SwiftWeekly/swiftweekly.github.io/issues/new'
  pull: 'https://github.com/SwiftWeekly/swiftweekly.github.io/compare'

authors:
  jsq:
    name: 'Jesse Squires'
    twitter: '@jesse_squires'
    url: 'https://twitter.com/jesse_squires'
    
exclude: [vendor]
